// Imports a week-by-week "scheme of work" for each course from the real
// FUTO CS curriculum's course descriptions (read directly from photos,
// not generated from titles alone — each week below is grouped from that
// course's actual "Course Contents" paragraph). Safe to re-run: replaces
// a course's scheme_of_work entirely by course_code, so re-running after
// fixing a typo below just overwrites rather than duplicating.
//
// Two deliberate omissions, not oversights:
//   - CHM 107 has no available content specification (confirmed) — given
//     a single row using its title as the topic, rather than an invented
//     multi-week breakdown with no real source behind it.
//   - SIW 200 and SIW 400 (SIWES) are supervised industrial placements,
//     not taught courses with a weekly syllabus — they're left with no
//     scheme_of_work at all rather than a fabricated one.
//
// Usage (from unilearn-server/, with a real .env in place):
//   node scripts/importSchemeOfWork.js

require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Course = require('../models/Course');

const w = (week, topic, details) => ({ week, topic, details });

const SCHEME_OF_WORK = {

  // ==================== 100 LEVEL — HARMATTAN ====================

  'COS 101': [
    w('Week 1', 'History & Basics', 'Brief history of computing; basic components of a computer/computing device'),
    w('Week 2', 'I/O, Hardware & Software', 'Input/output devices and peripherals; hardware, software, and humanware'),
    w('Week 3', 'Computing Applications', 'Diverse and growing computer/digital applications'),
    w('Week 4', 'Information Processing', 'Information processing and its roles in society'),
    w('Week 5', 'The Internet', 'The Internet, its applications, and its impact on the world today'),
    w('Week 6', 'The Computing Discipline', 'Areas/programs of computing; job specializations; the future of computing'),
    w('Week 7', 'Lab: Hardware & Operating Systems', 'Basic computer parts; operating systems across desktops, laptops, tablets, smart boards, smartphones'),
    w('Week 8', 'Lab: Common Applications', 'Word processors, spreadsheets, presentation software, graphics'),
    w('Week 9', 'Lab: I/O Devices', 'Printers, scanners, projectors, smartboards'),
    w('Week 10', 'Lab: Internet & Research', 'Internet applications, browsers, search engines, accessing online resources'),
  ],
  'GST 111': [
    w('Week 1', 'Sound Patterns', 'Vowels, consonants, phonetics, and phonology'),
    w('Week 2', 'Word Classes', 'Lexical and grammatical words; definitions, forms, functions, usages, collocations'),
    w('Week 3', 'Sentence Structure', 'Structural and functional sentence types; simple and complex sentences'),
    w('Week 4', 'Grammar & Usage', 'Tense, mood, modality, and concord; language use in everyday life'),
    w('Week 5', 'Logical & Critical Thinking', 'Logic, syllogism, inductive and deductive reasoning, analogy, generalisation'),
    w('Week 6', 'Ethics in Communication', 'Ethical considerations; copyright rules and infringements'),
    w('Week 7', 'The Writing Process', 'Pre-writing, writing, post-writing, editing, proofreading, brainstorming, outlining, paragraphing'),
    w('Week 8', 'Writing Types', 'Summary, essays, letters, curriculum vitae, report writing, note-making'),
    w('Week 9', 'Comprehension Strategies', 'Types of reading, comprehension skills, 3RsQ; ICT in modern language learning'),
    w('Week 10', 'Public Speaking & Reporting', 'Word formation processes; logical/critical reasoning for presentations; public speaking and listening; report writing'),
  ],
  'MTH 101': [
    w('Week 1', 'Number Systems & Algebraic Foundations', 'Number systems, indices, surds, logarithms, polynomials'),
    w('Week 2', 'Polynomial Theory', 'Remainder and factor theorem, polynomial equations, partial fractions, fields'),
    w('Week 3', 'Inequalities & Induction', 'Inequalities; mathematical induction'),
    w('Week 4', 'Combinatorics', 'Permutations, combinations, binomial theorem'),
    w('Week 5', 'Sequences & Quadratics', 'Sequences and series; the quadratic equation; relation between roots and coefficients'),
    w('Week 6', 'Complex Numbers', 'Arithmetic on complex numbers, Argand diagram, De Moivre\u2019s theorem, nth roots'),
    w('Week 7', 'Set Theory', 'Elementary set theory, Venn diagrams, De Morgan\u2019s laws'),
    w('Week 8', 'Trigonometry I', 'Basic trig functions, addition formulae, identities, sine/cosine rules'),
    w('Week 9', 'Trigonometry II', 'Half-angle formulae, area of a triangle, trig equations, inverse trig functions'),
    w('Week 10', 'Functions & Limits', 'Function concept and notation, composition, exponential/log functions, limits and continuity'),
    w('Week 11', 'Differentiation', 'First principles, techniques, chain rule, Mean Value Theorem, L\u2019H\u00f4pital\u2019s rule, Taylor/Maclaurin series'),
    w('Week 12', 'Integration & Curve Sketching', 'Curve sketching; integration as inverse of differentiation; applications'),
  ],
  'PHY 101': [
    w('Week 1', 'Units & Vectors', 'Space and time; units and dimension; vectors and scalars'),
    w('Week 2', 'Kinematics', 'Differentiation of vectors: displacement, velocity, acceleration'),
    w('Week 3', 'Newton\u2019s Laws', 'Inertial frames, impulse, force, action at a distance, momentum conservation'),
    w('Week 4', 'Relative Motion & Equations of Motion', 'Relative motion; application of Newtonian mechanics; equations of motion'),
    w('Week 5', 'Conservation Principles', 'Conservative forces; conservation of linear momentum; kinetic energy and work'),
    w('Week 6', 'Potential Energy & Systems', 'Potential energy; system of particles; centre of mass'),
    w('Week 7', 'Rotational Motion', 'Torque, vector product, moment, rotation of coordinate axes, angular momentum'),
    w('Week 8', 'Circular Motion', 'Polar coordinates; conservation of angular momentum; circular motion'),
    w('Week 9', 'Moments of Inertia', 'Moments of inertia; gyroscopes and precession'),
    w('Week 10', 'Gravitation', 'Newton\u2019s law of gravitation; Kepler\u2019s laws; gravitational potential energy; escape velocity; satellite motion and orbits'),
  ],
  'PHY 107': [
    w('Week 1', 'Measurement & Error Analysis', 'Quantitative measurements; treatment of measurement errors'),
    w('Week 2', 'Mechanical & Electrical Systems', 'Meters, oscilloscope studies, mechanical systems, electrical/mechanical resonant systems'),
    w('Week 3', 'Light, Heat & Viscosity Experiments', 'Experiments on light, heat, viscosity, and related PHY 101/102 topics'),
    w('Week 4', 'Data Collection & Graphical Analysis', 'Physical techniques for observation, measurement, data collection, analysis, and deduction'),
  ],
  'STA 111': [
    w('Week 1', 'Statistical Data', 'Types, sources, and methods of collection'),
    w('Week 2', 'Data Presentation', 'Tables, charts, and graphs'),
    w('Week 3', 'Errors & Approximations', 'Errors and approximations in statistical work'),
    w('Week 4', 'Frequency Distributions', 'Frequency and cumulative distributions'),
    w('Week 5', 'Measures of Location & Dispersion', 'Measures of location, partition, and dispersion'),
    w('Week 6', 'Skewness & Kurtosis', 'Skewness and Kurtosis, and their utility in a data set'),
    w('Week 7', 'Rates, Ratios & Index Numbers', 'Rates, ratios, and index numbers'),
  ],
  'CHM 101': [
    w('Week 1', 'Reactions & Stoichiometry', 'Chemical reactions, equations, and stoichiometry'),
    w('Week 2', 'Atomic Structure', 'Atomic structure and the periodic classification of elements'),
    w('Week 3', 'Electronic Theory & Radioactivity', 'Electronic theory of atoms; radioactivity'),
    w('Week 4', 'Bonding & Solids', 'Ionic and covalent bonds; solids and their structure'),
    w('Week 5', 'Dipole Interactions', 'Dipole interactions and their effect on physical properties'),
    w('Week 6', 'Redox & Equilibrium', 'Redox reactions; chemical equilibrium'),
    w('Week 7', 'Electrochemistry', 'Elementary electrochemistry'),
    w('Week 8', 'Kinetic Theory of Gases', 'Introduction to kinetic properties of gases'),
    w('Week 9', 'Chemical Kinetics & Thermodynamics', 'Basic chemical kinetics and chemical thermodynamics'),
    w('Week 10', 'Metal Extraction', 'Principles of metal extraction'),
  ],
  'CHM 107': [
    w('Weeks 1-15', 'General Chemistry Practical I', ''),
  ],
  'GST 103': [
    w('Week 1', 'Introduction to Humanities', 'Definition and rationale of the humanities'),
    w('Week 2', 'Literature & the African Novel', 'Role of literature in the humanities; the contemporary African Novel'),
    w('Week 3', 'Poetry & Drama', 'African/Western poetry; dramatic art and its relevance in modern Nigeria; demonstrations and performances'),
    w('Week 4', 'Philosophy in the Humanities', 'Man\u2019s quest for certainty; materialism and idealism'),
    w('Week 5', 'Values & Concepts', 'Freedom, responsibility, obligation, the "good life", art and beauty'),
    w('Week 6', 'Reasoning', 'Relative and non-relative values; inductive arguments and scientific reasoning'),
    w('Week 7', 'African History', 'Exposure to African history \u2014 its role and relevance'),
    w('Week 8', 'African Art & Music', 'History and development of African art and music'),
    w('Week 9', 'Religion & the Meaning of Life', 'Religion; the meaning of life \u2014 past, present, and future'),
  ],
  'IGB 101': [
    w('Week 1', 'Foundations', 'Listening, speaking, reading, and writing in the approved 1961 orthography; the Igbo alphabet (Mkpuruedemede Igbo)'),
    w('Week 2', 'Word Classes & Structure', 'Nkejiasusu Igbo, Akaraedemede, Nkebiokwu Igbo'),
    w('Week 3', 'Phrases & Sentences', 'Nkebiahiri Igbo, Ahiriokwu Igbo, and sentence types'),
    w('Week 4', 'SVO Structure & Sound', 'Asusu Igbo dika Asusu SVO; vowel harmony (Ndakorita udaume); tone (Udaolu)'),
    w('Week 5', 'Translation & Composition', 'Ntughari (translation), Edemede/kompozishon (composition), Edemleta'),
    w('Week 6', 'Comprehension & Spoken Igbo', 'Aghota azaa, Nchikota, Ekwumekwu n\u2019asusu Igbo, Ikwu okwu n\u2019oha, Nsupe n\u2019Igbo'),
  ],
  'FRN 101': [
    w('Week 1', 'Greetings & Introductions', 'Basic greetings in French'),
    w('Week 2', 'The French Alphabet', 'French alphabet and vowels'),
    w('Week 3', 'Pronunciation & Accents', 'Pronunciation and accent marks'),
    w('Week 4', 'Articles', 'French grammar: articles'),
    w('Week 5', 'Verbs', 'French grammar: verbs and basic conjugation'),
  ],

  // ==================== 100 LEVEL — RAIN ====================

  'COS 102': [
    w('Week 1', 'Core Concepts of Computing', 'Introduction to core concepts of computing; problems and problem-solving; routine vs non-routine problems'),
    w('Week 2', 'Algorithms & Heuristics', 'Methods of solving computing problems; solvable and unsolvable problems'),
    w('Week 3', 'Solution Techniques', 'Abstraction, analogy, brainstorming, trial and error, hypothesis testing, reduction, means-end analysis, divide and conquer'),
    w('Week 4', 'Problem-Solving Process', 'General problem-solving process; solution formulation and design'),
    w('Week 5', 'Design Tools', 'Flowchart, pseudocode, decision table, decision tree'),
    w('Week 6', 'Implementation & Evaluation', 'Implementation, evaluation, and refinement; programming in C, Python, etc.'),
    w('Week 7', 'Lab: Algorithms & Flowcharts', 'Tools for algorithms and flowcharts; writing pseudocode'),
    w('Week 8', 'Lab: Programming Basics', 'Assignment statements, input/output statements, condition statements; demonstrating simple programs (Visual Basic, Python, C)'),
  ],
  'GST 112': [
    w('Week 1', 'Historical Foundations', 'Historical foundation of Nigerian culture and arts in pre-colonial times'),
    w('Week 2', 'Linguistic Groups', 'Major linguistic groups in Nigeria'),
    w('Week 3', 'Evolution of Nigeria', 'Gradual evolution of Nigeria as a political unit; colonial administration and amalgamation'),
    w('Week 4', 'Nationalist Movement', 'Formation of political parties; nationalist movement and the struggle for independence'),
    w('Week 5', 'Nation-Building Challenges', 'Military intervention in Nigerian politics; the Nigerian Civil War'),
    w('Week 6', 'Trade & Self-Reliance', 'Concepts of trade, economic development, and self-reliance among Nigerian peoples'),
    w('Week 7', 'Judiciary & Rights', 'Role of the judiciary in upholding fundamental rights; social justice and national development'),
    w('Week 8', 'Norms & Values', 'Acceptable norms and values of major ethnic groups; citizenship and civic responsibilities'),
    w('Week 9', 'National Re-orientation', 'Moral and national values; re-orientation strategies (OFN, WAI, WAIC, MAMSER, NOA)'),
    w('Week 10', 'Current Developments', 'Current socio-political and cultural developments in Nigeria'),
  ],
  'MTH 102': [
    w('Week 1', 'Functions of a Real Variable', 'Function of a real variable, graphs, limits, and idea of continuity'),
    w('Week 2', 'The Derivative', 'The derivative as the limit of rate of change'),
    w('Week 3', 'Techniques of Differentiation', 'Techniques of differentiation; extreme curve sketching'),
    w('Week 4', 'Integration Basics', 'Integration as the inverse of differentiation'),
    w('Week 5', 'Methods of Integration', 'Methods of integration; definite integrals'),
    w('Week 6', 'Applications of Integration', 'Application of definite integrals to areas and volumes'),
  ],
  'PHY 102': [
    w('Week 1', 'Electrostatics', 'Forces in nature; electric charge and its properties; methods of charging'),
    w('Week 2', 'Coulomb\u2019s Law & Field', 'Coulomb\u2019s law and superposition; electric field and potential'),
    w('Week 3', 'Gauss\u2019s Law & Capacitance', 'Gauss\u2019s law; capacitance; electric dipoles; energy in electric fields'),
    w('Week 4', 'Conductors, Insulators & DC Circuits', 'Conductors and insulators; DC circuits, current, voltage, resistance, Ohm\u2019s law, resistor combinations'),
    w('Week 5', 'Magnetic Fields', 'Magnetic fields; Lorentz force; Biot-Savart and Amp\u00e8re\u2019s laws; magnetic dipoles'),
    w('Week 6', 'Electromagnetic Induction', 'Dielectrics; energy in magnetic fields; electromotive force; electromagnetic induction; self and mutual inductance'),
    w('Week 7', 'Faraday, Lenz & Transformers', 'Faraday and Lenz\u2019s laws; step-up and step-down transformers'),
    w('Week 8', 'Maxwell\u2019s Equations & AC', 'Maxwell\u2019s equations; electromagnetic oscillations and waves; AC voltages and currents in inductors, capacitors, resistors'),
  ],
  'PHY 108': [
    w('Weeks 1-15', 'General Practical Physics II', 'Continuation of experiments designed for PHY 101 and PHY 102, extending beyond those already covered under PHY 107'),
  ],
  'GET 102': [
    w('Week 1', 'Design Thinking & Engineering Graphics', 'Introduction to design thinking and engineering graphics fundamentals'),
    w('Week 2', 'Orthogonal Projections', 'First and third angle orthogonal projections'),
    w('Week 3', 'Isometric Projection & Sectioning', 'Isometric projections; sectioning; conventional practices'),
    w('Week 4', 'Conic Sections', 'Conic sections and development'),
    w('Week 5', 'Sketching', 'Freehand and guided sketching \u2014 pictorial and orthographic'),
    w('Week 6', 'Solid Modelling', 'Visualization and solid modelling in design, prototyping, and product-making'),
    w('Week 7', 'Design Workspaces', 'User interfaces; design, drawing, animation, rendering, and simulation workspaces'),
    w('Week 8', 'Viewports & Shop Drawings', 'Sketching of 3D objects; viewports; sectioning to shop drawings in orthographic projections and perspectives'),
    w('Week 9', 'Sheet Metal & Materials', 'Automated viewports; sheet metal and surface modelling; material selection and rendering (Fusion 360, SolidWorks, Solid Edge)'),
  ],
  'CHM 102': [
    w('Week 1', 'Organic Formulae & Structure', 'Organic formulae and structure; homology and isomerism'),
    w('Week 2', 'Hybridization', 'Concepts of hybridization'),
    w('Week 3', 'Aliphatic & Aromatic Compounds', 'Survey of reactions of functional groups in aliphatic and aromatic compounds'),
    w('Week 4', 'Alkalines & Hydrocarbons', 'Chemistry of alkalines; alkenes, alkynes, halokanes, alkanols'),
    w('Week 5', 'Functional Groups', 'Esters, amines, aldehydes, ketones, carboxylic acids and their derivatives'),
  ],
  'CHM 108': [
    w('Weeks 1-15', 'General Chemistry Practical II', 'Continuation of CHM 107; additional laboratory experiments including functional group analysis and quantitative analysis using volumetric methods'),
  ],
  'STA 112': [
    w('Week 1', 'Permutation & Combination', 'Differences between permutation and combination'),
    w('Week 2', 'Probability Concepts', 'Concepts and principles of probability'),
    w('Week 3', 'Random Variables', 'Random variables; relation to probability and distribution functions'),
    w('Week 4', 'Distribution Functions', 'Probability and distribution functions'),
    w('Week 5', 'Basic Distributions', 'Binomial, geometric, Poisson, normal, and sampling distributions'),
    w('Week 6', 'Exploratory Data Analysis', 'Concept of exploratory data analysis'),
  ],
  'EGL 102': [
    w('Week 1', 'Common Errors in English', 'Wrong use of articles, adjectives, adverbs, prepositions; words commonly confused'),
    w('Week 2', 'Agreement & Concord', 'Error of agreement (concord)'),
    w('Week 3', 'Academic & Technical Writing', 'Academic research reports; other advanced technical reports'),
    w('Week 4', 'Business Writing', 'Minutes writing, memorandum (memo), documentation, bibliography and references'),
    w('Week 5', 'Public Speaking', 'Types of speech; choosing a topic; gathering information; audience; visual aids in speech delivery'),
    w('Week 6', 'Advanced Reading Skills', 'Understanding highly technical passages through language clues'),
    w('Week 7', 'Literary Genres', 'Appreciation of different literary genres: prose, poetry, drama'),
    w('Week 8', 'Interview Skills', 'Essentials of a successful interview: preparation, dressing, manner of answering questions'),
  ],
  'IGB 102': [
    w('Week 1', 'Igbo Worldview', 'Igbo world-view; Igbo culture and history'),
    w('Week 2', 'Igbo in a World of Arts', 'Igbo in a world of arts and civilization'),
    w('Week 3', 'Igbo Literature', 'Exposure to Igbo literature embodying the totality of the Igbo world-view'),
    w('Week 4', 'Perspectives & Aspirations', 'Social and cultural perspectives, aspirations, and amenities'),
    w('Week 5', 'Contemporary Texts', 'Study of contemporary Igbo texts'),
  ],
  'FRN 102': [
    w('Week 1', 'French Grammar', 'French grammar proper'),
    w('Week 2', 'Dialogue & Oral Exercises', 'Dialogue and other oral exercises'),
    w('Week 3', 'Introduction to Reading', 'Reading, starting with France Afrique book 1'),
    w('Week 4', 'Speaking Basic French', 'Building toward speaking basic French'),
    w('Week 5', 'Telling Time', 'Telling time in French'),
  ],

  // ==================== 200 LEVEL — HARMATTAN ====================

  'CSC 201': [
    w('Week 1', 'History & Classification of Computers', 'Discipline of computer science; evolution of computer systems; classification of computers'),
    w('Week 2', 'Computer Hardware', 'Functional components; modern input/output units'),
    w('Week 3', 'Operating Systems', 'Computer software: UNIX, Windows, Linux/Ubuntu, Kali, Red Hat, etc.'),
    w('Week 4', 'Application Packages', 'Word processing, database packages (Oracle, MySQL, PostgreSQL), spreadsheet/statistical packages (Excel, SPSS)'),
    w('Week 5', 'Design & Project Software', 'Design/graphics (CAD, CorelDraw, Photoshop); project management processing systems'),
    w('Week 6', 'Number Systems', 'Data representation in digital computers; binary representation; addition and subtraction'),
    w('Week 7', 'Signed Number Representations', 'One\u2019s and two\u2019s complement; unsigned magnitude and excess radix representations'),
    w('Week 8', 'Networks & the Internet', 'Introduction to computer networks and the Internet'),
    w('Week 9', 'Modern Computing Trends', 'Smart computing and intelligent systems; IoT and machine learning; VR; cognitive technology; touch screen technology'),
    w('Week 10', 'Computer Security & Programming Tools', 'Computer security (benefits and challenges); ubiquitous computing; language translators (assembler, interpreter, compiler)'),
    w('Week 11', 'Program Development', 'Development environments (NetBeans, Visual Studio, JCreator, Adobe CS6); program development techniques: pseudocode, flowcharts, algorithms'),
    w('Week 12', 'Practical Programming', 'Computer programming in recent versions of Visual BASIC/C/C++/Java/Python'),
  ],
  'CSC 203': [
    w('Week 1', 'Overview of Cyber Security', 'Introductory topics: confidentiality, integrity, availability, authentication'),
    w('Week 2', 'Access Control & Non-Repudiation', 'Access control; non-repudiation; fault-tolerant methodologies for implementing security'),
    w('Week 3', 'Security Policies & Practices', 'Security policies; best current practices'),
    w('Week 4', 'Testing & Incident Response', 'Testing security; incident response'),
    w('Week 5', 'Risk Management & Recovery', 'Risk management; disaster recovery; access control'),
    w('Week 6', 'Cryptography & Vulnerabilities', 'Basic cryptography and software application vulnerability'),
  ],
  'MTH 201': [
    w('Week 1', 'Functions of Several Variables', 'Functions of two or more variables; limits and continuity'),
    w('Week 2', 'Partial & Directional Derivatives', 'Partial derivatives, directional derivatives, tangent plane and normal line'),
    w('Week 3', 'Gradient & Chain Rule', 'Gradient; chain rule; total differential; implicit functions'),
    w('Week 4', 'Jacobians & Inverse Functions', 'Jacobians, inverse functions, maxima and minima'),
    w('Week 5', 'Lagrange Multipliers', 'Lagrange multipliers; higher order derivatives; the Laplacian'),
    w('Week 6', 'Second Derivative Test', 'Second derivative test for maxima and minima; exact differentials'),
    w('Week 7', 'Taylor\u2019s Theorem & Multiple Integrals', 'Derivatives of integrals; Taylor\u2019s theorem; multiple integrals'),
    w('Week 8', 'Applications of Multiple Integrals', 'Calculation of areas, volumes, centres of mass, and moments of inertia'),
    w('Week 9', 'Sequences & Series', 'Infinite sequences and series; absolute and conditional convergence; power series'),
  ],
  'MTH 203': [
    w('Week 1', 'Origins of Differential Equations', 'Derivation of equations from physics, chemistry, biology, geometry, etc.'),
    w('Week 2', 'First Order Equations', 'First order equations; applications of first order equations'),
    w('Week 3', 'Second Order Linear Equations', 'Second order linear equations; fundamental solutions'),
    w('Week 4', 'Linear Independence & the Wronskian', 'Linear dependence and independence; the Wronskian'),
    w('Week 5', 'Properties of Solutions', 'Properties of solutions of linear equations'),
    w('Week 6', 'Undetermined Coefficients & Variation of Parameters', 'Method of undetermined coefficients; variation of parameters'),
    w('Week 7', 'Applications & n-th Order Equations', 'Applications of second order linear equations; general theory of n-th order linear equations'),
    w('Week 8', 'Laplace Transforms', 'Laplace transforms; convolution'),
    w('Week 9', 'Solving Initial-Value Problems', 'Solution of initial-value problems by Laplace transform methods; difference equations'),
  ],
  'STA 211': [
    w('Week 1', 'Frequency Distributions', 'Frequency distributions; measures of location and dispersion in simple and grouped data'),
    w('Week 2', 'Laws of Probability', 'Laws of probability'),
    w('Week 3', 'Key Distributions', 'Binomial, Poisson, and normal distributions'),
    w('Week 4', 'Estimation & Hypothesis Testing', 'Estimation and tests of hypothesis'),
    w('Week 5', 'Analysis of Variance & Covariance', 'Analysis of variance and covariance'),
    w('Week 6', 'Regression & Correlation', 'Simple regression and correlation; contingency tables and chi-square'),
    w('Week 7', 'Descriptive Displays', 'Descriptive methods \u2014 stem and leaf charts; graphical displays: box and whisker plots'),
  ],
  'PHY 201': [
    w('Week 1', 'DC Circuit Theory', 'Electrical circuit theory: DC circuit analysis'),
    w('Week 2', 'AC Circuit Analysis', 'AC circuit analysis'),
    w('Week 3', 'Magnetic Circuits', 'Magnetic circuit: magnetomotive force, magnetic flux and reluctance'),
    w('Week 4', 'Magnetic Permeability', 'Relative magnetic permeability and susceptibility'),
    w('Week 5', 'Electrical Machines', 'Introduction to electrical machines: DC generator, DC motor'),
    w('Week 6', 'Polyphase Systems & Transformers', 'Polyphase systems; transformers; electric power distribution'),
    w('Week 7', 'Instruments & Illumination', 'Electric lamps and illumination; galvanometers, ammeters, and voltmeters'),
  ],
  'ENG 201': [
    w('Week 1', 'Manufacturing Technology Basics', 'Introduction to manufacturing technology; basic foundry technology'),
    w('Week 2', 'Sand Testing & Mould Preparation', 'Sand testing, mixing of sands, preparation of moulds'),
    w('Week 3', 'Pattern Making', 'Pattern making \u2014 solid, split, sweep patterns; gates and risers'),
    w('Week 4', 'Casting Processes', 'Melting and pouring of metals; solidification; casting using sand moulds, permanent moulds, expendable polystyrene'),
    w('Week 5', 'Casting Defects & Joint Design', 'Casting defects; design of welded joints (T, BUTT, corner/cap joints)'),
    w('Week 6', 'Joining Techniques', 'Stress analysis of joints; soldering, brazing, adhesive joints; fusion welds (manual metal arc, TIG, SAW, spot, etc.)'),
    w('Week 7', 'Edge Preparation & Weld Strength', 'Edge preparation, surface cladding; strength and toughness of welded joints; laser and RF welding'),
  ],
  'GST 201': [
    w('Week 1', 'Development & Traditional Africa', 'Concept and meaning of development; traditional Africa\u2019s geographical and ethnographical review'),
    w('Week 2', 'Family & Political Structures', 'Family structure, kinship system; political systems'),
    w('Week 3', 'Socio-Economic Life & the Arts', 'Socio-economic pre-occupations; art and processes of music'),
    w('Week 4', 'Communication & Modernization', 'Modes of communication; modernization \u2014 education, writing and press'),
    w('Week 5', 'Urbanization & Social Change', 'Urbanization and social change; modern trends in art and aesthetics'),
    w('Week 6', 'Nationalism & Development', 'Nationalism and cultural revival; mass media and national development'),
  ],

  // ==================== 200 LEVEL — RAIN ====================

  'CSC 202': [
    w('Week 1', 'Discipline of Computer Science', 'Evolution of computer systems; classification of computers'),
    w('Week 2', 'Computer Hardware & Software', 'Functional components, I/O units; operating systems (UNIX, Windows, Linux)'),
    w('Week 3', 'Application Packages', 'Word processing, spreadsheets, database packages; CAD, graphics tools'),
    w('Week 4', 'Number Systems', 'Binary number representation; addition and subtraction; signed magnitude and excess radix'),
    w('Week 5', 'Networks & Modern Computing', 'Introduction to computer networks and the Internet; smart computing, IoT, machine learning, VR'),
    w('Week 6', 'Programming Tools & Techniques', 'Language translators; program development techniques: pseudocode, flowcharts, algorithms'),
    w('Week 7', 'Programming Practice', 'Implementation strategies; implementation of algorithms in Visual Basic, Java, or C/C++'),
  ],
  'CIT 204': [
    w('Week 1', 'Computer Systems Review', 'Review of computer systems basic structure and types; differences between architecture and organization'),
    w('Week 2', 'Fetch-Execute Cycle', 'Review of computer operation, fetch and execute cycle, interrupts, stack operations'),
    w('Week 3', 'Architecture Types', 'Von Neumann, multicore, and multiprocessor systems'),
    w('Week 4', 'Instruction Set Architecture', 'CISC, RISC, VLIW, EPIC architectures'),
    w('Week 5', 'Core Hardware Components', 'Review of computer hardware system components: CPU, memory, I/O systems'),
    w('Week 6', 'Microprocessors', 'Internal architecture and system components; types of microprocessors'),
    w('Week 7', 'Memory Systems', 'Memory types: semiconductor, optical, magnetic; standards; memory hierarchy'),
    w('Week 8', 'I/O Systems Design', 'I/O systems design and types; microcomputer system organization and operation'),
    w('Week 9', 'Bus & Control Architecture', 'Bus architecture and standards; hardware control and micro-programmed control'),
    w('Week 10', 'DMA & Interrupt Systems', 'Direct memory access (DMA) and interrupt systems'),
    w('Week 11', 'Computer Arithmetic & Logic', 'Computer arithmetic and logic; Boolean algebra and logic gates'),
    w('Week 12', 'Circuit Design', 'Combinational and sequential circuit design and applications: decoders, multiplexers, adders, registers, counters'),
    w('Week 13', 'Assembly Programming', 'Assembly language programming, addressing modes; design assignments'),
  ],
  'CIT 202': [
    w('Week 1', 'Problem Solving Process', 'Problem identification; formal representation of the problem; identification of inputs and outputs'),
    w('Week 2', 'Algorithm Concepts', 'Concept and properties of algorithms; algorithm development using pseudocodes and flowcharts'),
    w('Week 3', 'Choosing a Language & Style', 'Choice of programming language (Python, Visual Basic, Java, C/C++); procedural, modular, and object-oriented styles'),
    w('Week 4', 'Data Types & Structures', 'Data types, keywords, operators; data structures'),
    w('Week 5', 'Control Structures', 'Sequence, selection, and repetition'),
    w('Week 6', 'String & File Processing', 'String processing; file processing techniques'),
    w('Week 7', 'Parameter Passing & Binding', 'Passing by value and passing by reference; static and dynamic binding'),
    w('Week 8', 'Storage & Debugging', 'Storage allocation techniques; program debugging'),
    w('Week 9', 'Testing & Documentation', 'Program testing and documentation; programming laboratory exercises'),
  ],
  'MTH 202': [
    w('Week 1', 'Vectors & Vector Spaces', 'Vectors; products of vectors; equations of lines and planes; vector spaces'),
    w('Week 2', 'Linear Dependence & Basis', 'Linear dependence and independence; basis and dimension'),
    w('Week 3', 'Linear Transformations & Matrices', 'Linear transformations; matrices'),
    w('Week 4', 'Determinants & Inverses', 'Determinants; operations on matrices; inverse of a matrix; Cramer\u2019s rule'),
    w('Week 5', 'Eigenvalues & Diagonal Matrices', 'Rank of a matrix; eigenvalues and eigenvectors; similarities to diagonal matrices'),
  ],
  'CSC 204': [
    w('Week 1', 'OS Protection Mechanisms', 'Operating system protection mechanisms; intrusion detection systems'),
    w('Week 2', 'Formal Security Models', 'Formal models of security; cryptography; stenography'),
    w('Week 3', 'Network & Distributed Security', 'Network and distributed system security; denial of service and other attack strategies'),
    w('Week 4', 'Malware & Fund Transfer Security', 'Worms and viruses; transfer of funds/value across networks'),
    w('Week 5', 'Electronic Voting & Secure Applications', 'Electronic voting; secure applications; homeland cyber security policy'),
    w('Week 6', 'Government Regulation', 'Government regulation of information technology'),
  ],
  'CSC 208': [
    w('Week 1', 'Databases & Users', 'Databases and database users; file systems and DBMS; database applications'),
    w('Week 2', 'Database Concepts', 'Database concepts: models, schemas, instances'),
    w('Week 3', 'DBMS Architectures', 'Centralized and client/server architectures for DBMSs; classification of DBMSs'),
    w('Week 4', 'Relational Models & SQL', 'Relational database models; basic SQL'),
    w('Week 5', 'ER & UML Modelling', 'ER and UML models; role of information systems in organizations'),
    w('Week 6', 'Database Design & Implementation', 'Database design and implementation process using Microsoft Access'),
  ],
  'MTH 222': [
    w('Week 1', 'Solving Equations & Interpolation', 'Solution of algebraic and transcendental equations; Lagrange and Aitken interpolating polynomials'),
    w('Week 2', 'Difference Calculus & Curve Fitting', 'Difference calculus; Newton forward and backward difference formulae; curve fitting'),
    w('Week 3', 'Errors & Approximation', 'Errors; approximation of functions'),
    w('Week 4', 'Numerical Differentiation & Integration', 'Numerical differentiation and integration'),
    w('Week 5', 'Numerical Solution of Linear Systems', 'Numerical solution of systems of linear equations'),
    w('Week 6', 'Numerical Methods for Differential Equations', 'Numerical methods for solving differential equations'),
  ],
  'STA 212': [
    w('Week 1', 'Probability Spaces & Random Variables', 'Probability spaces, random variables, distribution function, expected value'),
    w('Week 2', 'Discrete & Continuous Distributions', 'Examples of discrete and continuous distributions'),
    w('Week 3', 'Mean, Variance & Moments', 'Mean, variance, moments, and generating functions'),
    w('Week 4', 'Conditional Probability & Bayes', 'Conditional probability; Bayes theorem'),
    w('Week 5', 'Joint Distributions', 'Joint distributions of transformed random variables'),
    w('Week 6', 'Limit Theorems', 'Chebychev\u2019s inequality; law of large numbers; central limit theorem'),
    w('Week 7', 'Multivariate Normal & Covariance', 'Multivariate normal distribution; co-variance and correlation'),
  ],

  // ==================== 300 LEVEL — HARMATTAN ====================

  'CIT 301': [
    w('Week 1', 'History of Operating Systems', 'Review of historical development of operating systems; operating system concepts and structure'),
    w('Week 2', 'Kernel & Process Management', 'Basic components of a modern OS; operating system kernel; processor management: concurrency control'),
    w('Week 3', 'Inter-Process Communication', 'Process and inter-process communication; process synchronization; deadlocks'),
    w('Week 4', 'Memory & Device Management', 'Memory management; device management; file systems, protection, and security'),
    w('Week 5', 'Case Studies of Real OSes', 'Case studies of features of popular OSes: MS Windows, Unix, Linux'),
    w('Week 6', 'OS Design Features', 'Design features of single-user, multi-user, network, distributed, real-time, and embedded operating systems'),
    w('Week 7', 'Lab: Installation & Maintenance', 'Installation and maintenance of Windows and Unix-like OSes such as Linux'),
    w('Week 8', 'Lab: Shell Scripting', 'Writing programs that interact with the OS; shell scripts and batch files; pattern matching, editing, micro processing, data/text analysis'),
  ],
  'CIT 303': [
    w('Week 1', 'System Concepts', 'System concepts; system components; introduction to SSAD'),
    w('Week 2', 'System Development Life Cycle', 'Project planning; requirements specification'),
    w('Week 3', 'Analysis & Fact Gathering', 'Analysis; preliminary investigation; fact-gathering techniques'),
    w('Week 4', 'Data Delivery & DFDs', 'Data delivery; data flow diagrams; process description'),
    w('Week 5', 'System Design Tools', 'Automated design tools; data modeling; structure charts'),
    w('Week 6', 'I/O, Reports & Security', 'I/O and report form designs; security; data dictionary'),
    w('Week 7', 'Software Design & Implementation', 'Software design and coding; system implementation: software development, hardware acquisition'),
    w('Week 8', 'Integration, Testing & Maintenance', 'System integration and testing; cost and time estimation; system maintenance; case studies and projects'),
  ],
  'CSC 303': [
    w('Week 1', 'System Unit Hardware', 'Basic computer hardware: input/output devices; internal components (motherboard, memory banks, expansion slots)'),
    w('Week 2', 'Interconnections & Maintenance', 'Hardware component interconnections; computer maintenance, cloning, and assembly'),
    w('Week 3', 'Interfaces & Networking', 'Computer interfaces and cables; computer networks and data communications devices'),
    w('Week 4', 'System Security', 'Computer system security; data protection techniques'),
    w('Week 5', 'Lab: Application Software', 'Practical laboratory experience with word processors, spreadsheets, database packages'),
    w('Week 6', 'Lab: Project & Decision Systems', 'Project management systems; decision support systems'),
    w('Week 7', 'Lab: Graphics & Web Tools', 'Computer graphics; web design tools; Internet facilities'),
  ],
  'CSC 305': [
    w('Week 1', 'Abstract Data Types', 'Abstract data types; record structure; file structure'),
    w('Week 2', 'Arrays, Lists & Linked Lists', 'Arrays/lists; linked lists; algorithms for implementation and operations'),
    w('Week 3', 'Stacks & Queues', 'Stacks and queues; implementation and operations'),
    w('Week 4', 'Trees & Graphs', 'Trees, graphs; algorithms for finding paths and spanning trees'),
    w('Week 5', 'Sorting & Searching', 'Design and analysis of efficient algorithms for searching, internal/external sorting, and merging'),
    w('Week 6', 'Dynamic Storage Allocation', 'Algorithms for dynamic storage allocation, garbage collection, and compaction'),
    w('Week 7', 'Database Integration', 'Integration of data structures, and searching/sorting/merging methods and memory media into a simple database management system'),
  ],
  'CSC 307': [
    w('Week 1', 'Structured Programming Elements', 'Structured programming elements; programming abstractions'),
    w('Week 2', 'Structured Design Principles', 'Structured design principles; modular programming'),
    w('Week 3', 'Data Structures in Structured Design', 'Data structures; structured program design techniques and tools'),
    w('Week 4', 'Structured Object-Oriented Programming', 'Structured object-oriented programming; stepwise refinement'),
    w('Week 5', 'Advanced Features', 'Advanced features of structured programming languages such as C/C++, Java, etc.'),
  ],
  'CSC 309': [
    w('Week 1', 'Basic Set Theory', 'Basic set theory; basic definitions'),
    w('Week 2', 'Relations & Ordered Sets', 'Relations; equivalence relation; partition; ordered sets'),
    w('Week 3', 'Logic', 'Logic (propositional and related concepts)'),
    w('Week 4', 'Graph Theory', 'Graph theory; directed and undirected graphs; graph isomorphism; basic graph theorems'),
    w('Week 5', 'Boolean Algebra & Lattices', 'Boolean algebra and lattices'),
    w('Week 6', 'Matrices', 'Matrices: integer and real matrices; Boolean matrices; matrix norms'),
    w('Week 7', 'Adjacency & Path Matrices', 'Adjacency vectors/matrices; path matrices; Boolean adjacency matrices'),
    w('Week 8', 'Combinatorics & Generating Functions', 'Numerical and Boolean matrices applied to counting; discrete probability generating functions'),
  ],
  'PHY 303': [
    w('Week 1', 'Semiconductor Devices', 'Semiconductor devices: semiconductors, diodes, transistors, integrated circuits'),
    w('Week 2', 'Diode Characteristics', 'Diode characteristic curves; forward and reverse bias; rectification and filtering'),
    w('Week 3', 'Zener Diodes & Voltage Regulation', 'Zener diode; diode voltage regulators'),
    w('Week 4', 'Transistors', 'Bipolar and field effect transistors; characteristic curves; active and cut-off regions'),
    w('Week 5', 'Transistor Amplifiers', 'Transistor amplifiers, bipolar and FET amplifiers, biasing and load lines'),
    w('Week 6', 'Operational Amplifiers', 'Operational amplifiers: negative feedback; analog computation'),
    w('Week 7', 'Feedback & Oscillators', 'Positive feedback; oscillators; waveform generators'),
  ],
  'CIT 305': [
    w('Week 1', 'Software Techniques & Process Models', 'Introduction to software techniques, methodologies, and process models'),
    w('Week 2', 'Specification & Requirements', 'Specification modelling; requirements analysis and definition'),
    w('Week 3', 'Agile Development', 'Agile software development'),
    w('Week 4', 'Software Design', 'Software design; quality assurance'),
    w('Week 5', 'Testing & Tooling', 'Testing; development tools and environments'),
    w('Week 6', 'Ethics & Dependability', 'Software engineering ethics; introduction to software management, dependability, and security assurance'),
  ],
  'ENS 301': [
    w('Week 1', 'Entrepreneurship & the Nigerian Environment', 'Development of entrepreneurship; the Nigerian entrepreneurial environment'),
    w('Week 2', 'Creativity & IP Rights', 'Creativity and intellectual rights; technological entrepreneurship'),
    w('Week 3', 'Innovation & Succession Planning', 'Innovation: theories and management; family business and succession planning'),
    w('Week 4', 'Social Entrepreneurship', 'Women entrepreneurship; social entrepreneurship'),
    w('Week 5', 'Opportunity & Strategy', 'Business opportunity set and evaluation; introduction to business strategy'),
    w('Week 6', 'Ethics & Governance', 'Introduction to business ethics and corporate governance'),
    w('Week 7', 'Research, Innovation & Products', 'Relationship between scientific research innovation and products; timeliness and processes'),
  ],
  'MTH 303': [
    w('Week 1', 'Sets, Functions & Induction', 'Sets; functions; mathematical induction'),
    w('Week 2', 'Properties of Real Numbers', 'Properties of real numbers; Cauchy convergence criterion'),
    w('Week 3', 'Convergence Tests', 'Tests for convergence'),
    w('Week 4', 'Limits & Continuity', 'Limits and continuity of functions; uniform continuity of functions'),
    w('Week 5', 'Uniform Continuity & Approximations', 'Uniform continuity and approximations'),
    w('Week 6', 'The Derivative & Mean Value Theorem', 'The derivative; Mean Value Theorem; L\u2019H\u00f4pital\u2019s rule'),
    w('Week 7', 'Taylor\u2019s Theorem & Convex Functions', 'Taylor\u2019s theorem; convex functions; applications'),
  ],
  'STA 311': [
    w('Week 1', 'Point Estimation', 'Point estimation by moments and maximum likelihood methods'),
    w('Week 2', 'Properties of Estimators', 'Unbiasedness, sufficiency, completeness; uniformly minimum variance unbiasedness'),
    w('Week 3', 'Rao-Cramer & Consistency', 'Rao-Cramer inequality; consistency, efficiency, asymptotic normality'),
    w('Week 4', 'Confidence Intervals', 'Confidence intervals and regions; general method of finding a confidence bound'),
    w('Week 5', 'Large Sample & Bayesian Methods', 'Large sample confidence intervals; Bayesian method of estimation'),
    w('Week 6', 'Hypothesis Testing', 'Hypothesis testing; Neyman-Pearson theorem'),
    w('Week 7', 'Comparison of Populations', 'Comparison of populations by parametric methods'),
  ],
  'CSC 311': [
    w('Week 1', 'Statistical Packages', 'Explanation of statistical packages'),
    w('Week 2', 'Stochastic & Linear Models', 'Problems associated with analysis of stochastic problems and statistical data analysis by applied linear models'),
    w('Week 3', 'Regression Modelling', 'Computational aspects of multiple regression model; programming for statistical problems and statistical packages'),
    w('Week 4', 'Sampling Surveys', 'Design and analysis of sampling surveys; statistical data compression; 2D/3D frequency tables'),
    w('Week 5', 'Estimation & Hypothesis Testing', 'Point and interval estimation; test of significance; test of hypothesis'),
    w('Week 6', 'Categorical Data & Model Validation', 'Analysis of categorical data; model validation; chi-square test'),
    w('Week 7', 'Multiple Regression & ANOVA', 'Multiple regressions; analysis of variance; statistical control; use of statistical packages'),
  ],

  // ==================== 300 LEVEL — RAIN ====================

  'CSC 310': [
    w('Week 1', 'OS Design Approaches', 'OS design approaches: layered, kernel, and virtual machine'),
    w('Week 2', 'File Systems & I/O Management', 'File systems and management; I/O management: goals of I/O software'),
    w('Week 3', 'Device Controllers & DMA', 'Device controllers; direct memory access; disk hardware'),
    w('Week 4', 'Disk Scheduling', 'Disk arm scheduling algorithms; memory-mapped terminals'),
    w('Week 5', 'Advanced Memory Management', 'Advanced memory management schemes and algorithms; caching; virtual memory'),
    w('Week 6', 'Process Scheduling & Concurrency', 'Processor management and process scheduling; concurrency control'),
    w('Week 7', 'Deadlocks & Error Handling', 'Deadlock detection and prevention algorithms; interrupt handlers; error handling'),
    w('Week 8', 'Case Studies', 'Case study: Unix, Linux, Windows, real-time operating systems'),
  ],
  'CSC 302': [
    w('Week 1', 'CPU Organization Review', 'Review of CPU organization and micro-architectural level designs'),
    w('Week 2', 'Instruction Set Design', 'Instruction set designs, register transfer, CISC and RISC design principles'),
    w('Week 3', 'Instruction Set Architecture', 'Instruction types, registers, and memory addressing modes'),
    w('Week 4', 'Bus & Data-Path Design', 'Bus organization and data-path design'),
    w('Week 5', 'Control Unit Design', 'Hardwired and micro-programmed control; internal control signals'),
    w('Week 6', 'ALU Design & Arithmetic', 'ALU operation and design; integer/floating point data representations; addition, multiplication, division algorithms'),
    w('Week 7', 'Floating Point & Memory Systems', 'Floating point processors; BCD arithmetic; memory systems and their characteristics'),
    w('Week 8', 'Recording Technology & Peripherals', 'Technology of magnetic recording, optical, and semiconductor memories; peripheral device designs'),
  ],
  'CIT 304': [
    w('Week 1', 'Information Organization', 'Organization of information for storage and retrieval; concepts of fields, records, files, and databases'),
    w('Week 2', 'File Organization & Access', 'Data storage devices and characteristics; file organization and access methods'),
    w('Week 3', 'Hashing & Blocking', 'Relative file organization and hashing algorithms; record blocking factors'),
    w('Week 4', 'Multimedia Files', 'Classification of files: master, transaction, history/trends; multimedia files'),
    w('Week 5', 'Data Verification & Records', 'Data verification and validation methods; records/files creation and manipulation'),
    w('Week 6', 'Information & File Security', 'Information and file security; concurrency and data integrity'),
    w('Week 7', 'Processing Modes & Reports', 'Data file processing modes: batch, online, real-time; report generation'),
    w('Week 8', 'Case Studies', 'Case studies, designs, and algorithms'),
  ],
  'CIT 302': [
    w('Week 1', 'Data Types & Structures', 'Review of data types and structure; numeric and string types, arrays, pointers'),
    w('Week 2', 'Program Environments', 'Program environments and operating systems facilities available to the programmer'),
    w('Week 3', 'Array Algorithms', 'Implementation of algorithms for arrays handling, enumerated data types, strings'),
    w('Week 4', 'Searching, Sorting & Recursion', 'Searching, sorting, linked lists, recursion; input/output file access and updating'),
    w('Week 5', 'Good Programming Principles', 'Structured, modular, and defensive programming; object orientation revisited'),
    w('Week 6', 'Java IDE & Core Concepts', 'Java IDE (creating, saving, opening program files); classes and methods; inputs/outputs, variables/constants'),
    w('Week 7', 'Iteration & Data Manipulation', 'Iteration, decision, operations, data manipulations'),
    w('Week 8', 'Advanced OOP Concepts', 'Inheritance, polymorphism, encapsulation, exception handling; Java I/O, file manipulation'),
    w('Week 9', 'Other Languages & Tools', 'C++, HTML, XML; Oracle suites, ASP.Net, IIS, Apache'),
  ],
  'CIT 306': [
    w('Week 1', 'Internet Infrastructure', 'Introduction to the WWW; Internet hardware infrastructures; review of the ISO interconnectivity model'),
    w('Week 2', 'Internet Software & Protocols', 'Internet information communication infrastructures; Internet software systems; Internet-based system architectures'),
    w('Week 3', 'Server Technology', 'Protocols design; HTTP, TCP/IP, MIME, URLs, CGI; server technology'),
    w('Week 4', 'HTML & Web Structure', 'Organization of WWW databases; HTML document structure \u2014 images, links, maps, tables, frames, forms'),
    w('Week 5', 'CSS & Styling', 'JavaScript syntax, DOM, forms processing; CSS fundamentals and positioning; web design and usability'),
    w('Week 6', 'XML & Multimedia', 'Introduction to XML syntax, DTDs, XSL, XHTML; multimedia audio, video, animation'),
    w('Week 7', 'Web Design Tools', 'Web design and development tools: Dreamweaver, Macromedia Flash, HTML, JavaScript, PHP, CGI'),
    w('Week 8', 'Web Security & Projects', 'Business-to-business websites; web data security \u2014 threat detection and data protection techniques; mini-projects on website design, implementation, and testing'),
  ],
  'CSC 304': [
    w('Week 1', 'Compilers, Assemblers & Interpreters', 'Review of compilers, assemblers, and interpreters; basic structure of a compiler'),
    w('Week 2', 'Phases of Compilation', 'Phases of compilation: lexical analysis, syntax analysis, semantic analysis, code generation'),
    w('Week 3', 'Code Optimization', 'Code optimization; grammars and languages; ambiguity in grammar'),
    w('Week 4', 'Parsing Techniques', 'Parsing techniques; symbol tables; storage administration'),
    w('Week 5', 'Error Handling & Intermediate Code', 'Error handling; intermediate codes; optimization and code generation'),
    w('Week 6', 'Automata & Compiler-Compilers', 'Deterministic and non-deterministic finite automata; compiler-compilers and translator writing systems; LEX and YACC'),
  ],
  'CSC 306': [
    w('Week 1', 'Assembler Concepts', 'Assembler concepts: assembler structure; data-word definition'),
    w('Week 2', 'Instructions & Directives', 'Instruction mnemonics and syntax; assembler directives and commands'),
    w('Week 3', 'Program Execution & Registers', 'Assembly programs execution; internal registers; error flags and messages'),
    w('Week 4', 'Addressing & Symbolic Addresses', 'Literals; instruction set and instruction formats; operand addressing mode; symbolic addresses'),
    w('Week 5', 'Register Transfer & Numeric Conversion', 'Register transfer languages, machine cycles; MIPS architecture/Intel processor assembly programming; numeric conversions'),
    w('Week 6', 'Macros & I/O Services', 'String processing; macros, I/O services; program control'),
    w('Week 7', 'Fetch-Execute & Interfacing', 'Fetch-execute cycle I/O operations; interfacing assembly language programs to high-level language programs'),
    w('Week 8', 'Case Studies', 'Machine instructions and microprogramming; case studies of ROMBIOS, NetBIOS, I/O control programs'),
  ],
  'ENS 302': [
    w('Week 1', 'Business & Value Creation', 'Concept of business and new value creation; introduction to theories of growth'),
    w('Week 2', 'Business Strategy & Capital', 'Business strategy; sources of capital; principles of marketing'),
    w('Week 3', 'Ethics & Social Responsibility', 'Business ethics and social responsibility'),
    w('Week 4', 'Expansion & E-Commerce', 'Opportunity sets and expansion considerations (e-commerce, e-business, e-trade)'),
    w('Week 5', 'The Engineer as Entrepreneur', 'The scientific/engineer as an entrepreneur; opportunities and challenges'),
    w('Week 6', 'Managing Transition', 'Managing transition (start-up, growth); basic accounting literacy'),
    w('Week 7', 'Feasibility & Cash Flow', 'Feasibility and viability studies including issues in cash flow analysis'),
    w('Week 8', 'Business Plans & Governance', 'Crafting business plans; corporate governance and change management'),
  ],
  'CSC 308': [
    w('Week 1', 'Formal Languages', 'Basics of formal languages with applications to syntax of programming languages'),
    w('Week 2', 'Models of Computation', 'Models of computers including finite automata, transducers'),
    w('Week 3', 'Turing Machines', 'Turing machines'),
    w('Week 4', 'Unsolvable Problems', 'Unsolvable problems and their relevance to the semantics of programming languages'),
    w('Week 5', 'Computational Complexity', 'Concept of computational complexity including NP-completeness'),
  ],
  'MTH 304': [
    w('Week 1', 'The Riemann Integral', 'The Riemann integral; fundamental theorem of calculus'),
    w('Week 2', 'Improper & Riemann-Stieltjes Integrals', 'Improper integrals; Riemann-Stieltjes integral'),
    w('Week 3', 'Sequences & Series of Functions', 'Sequences and series of functions; pointwise and uniform convergence'),
    w('Week 4', 'Functions of Several Variables', 'Functions of several variables; limits and continuity'),
    w('Week 5', 'The Derivative in R^p', 'The derivative in R^p; chain rule; higher order derivatives'),
    w('Week 6', 'Extremum Problems', 'Extremum problems; integration of functions of several variables'),
  ],
  'CSC 312': [
    w('Week 1', 'Introduction to OOP', 'Introduction to object-oriented programming; basic object-oriented concepts'),
    w('Week 2', 'Data Abstraction & Encapsulation', 'Data abstraction, encapsulation, classes, objects, messages, methods'),
    w('Week 3', 'Inheritance & Polymorphism', 'Inheritance, polymorphism, aggregation'),
    w('Week 4', 'OO Analysis & Design', 'OO analysis and design using UML patterns and frameworks, components and component object models'),
    w('Week 5', 'Operators & Structured OO', 'Operators and overloading; structured OO program to C++, Java'),
    w('Week 6', 'Library Functions', 'Introduction to C++/Java and their library of functions'),
  ],

  // ==================== 400 LEVEL — HARMATTAN ====================

  'CSC 401': [
    w('Week 1', 'Overview of Programming Languages', 'History of programming languages; brief survey of programming paradigms'),
    w('Week 2', 'Effects of Scale', 'The effects of scale on programming methodology'),
    w('Week 3', 'Syntactic Structure', 'Language description: syntactic structure (expression notation, abstract syntax tree, lexical syntax, grammar)'),
    w('Week 4', 'Language Semantics', 'Language semantics (formal, informal, denotational, axiomatic, operational)'),
    w('Week 5', 'Type Declarations & Checking', 'Type declarations; overview of type-checking; garbage collection'),
    w('Week 6', 'Abstraction Mechanisms', 'Abstraction mechanisms: procedures, functions, iteration; parameterized types; modules'),
    w('Week 7', 'Programming Paradigms', 'Object-oriented language paradigm; functional and logic language paradigms'),
  ],
  'CIT 401': [
    w('Week 1', 'DBMS Goals & Models', 'Goals of DBMS; database system models: relational, hierarchical, network, temporal, object-oriented'),
    w('Week 2', 'Data Modeling & Normal Forms', 'Data dependencies; schema refinements; normal forms; data decomposition'),
    w('Week 3', 'Query Languages', 'Relational calculus; relational algebra; query languages'),
    w('Week 4', 'Indexing', 'File organization and indexing: tree-structured, hash-based indexing'),
    w('Week 5', 'Integrity, Security & Recovery', 'Concurrency control; data protection; database system failures and recovery'),
    w('Week 6', 'Warehousing & Mining', 'Database warehousing and mining; advanced database management systems'),
    w('Week 7', 'Advanced Query & Automation', 'Advanced query languages; database systems design automation; intelligent query processing'),
    w('Week 8', 'Large & Multimedia Databases', 'Very large databases; data mining and information retrieval; high-dimensional database accesses (KDB-tree, R*-tree, AB-tree)'),
    w('Week 9', 'Web & Search Databases', 'Feature vectors and image databases; multimedia indexing; web databases and search engines; security issues; case studies and projects'),
  ],
  'CSC 403': [
    w('Week 1', 'Computer Circuits', 'Computer circuits: diode arrays, programmable logic arrays'),
    w('Week 2', 'Integrated Circuit Fabrication', 'Computer major integrated circuits; fabrication process of SSI, MSI, LSI, VLSI, WSI circuits'),
    w('Week 3', 'ALU Circuit Design', 'ALU circuits design; control unit circuit design'),
    w('Week 4', 'Storage Media Design', 'Design and characterization of magnetic disks and tapes; optical disks; semiconductor memories; flash memories'),
    w('Week 5', 'Peripheral Device Design', 'Design features of peripheral devices: CRTs, keyboards, mouse, light pens, printers, scanners'),
    w('Week 6', 'Character Recognition & Converters', 'Character recognition devices; I/O interface/control circuits design; analog-to-digital and digital-to-analog converters'),
    w('Week 7', 'Diagnostics', 'Operational amplifiers; hardware diagnostic tools'),
  ],
  'CSC 405': [
    w('Week 1', 'Asymptotic Analysis', 'Basic algorithmic analysis: asymptotic analysis of upper and average complexity bounds'),
    w('Week 2', 'Complexity Classes & Tradeoffs', 'Standard complexity classes; time and space tradeoffs in algorithm analysis'),
    w('Week 3', 'Recursive & Set Algorithms', 'Recursive algorithms; algorithms for unordered and ordered sets, graphs, matrices'),
    w('Week 4', 'Arithmetic Algorithms', 'Algorithms for integer arithmetic, real arithmetic, polynomial arithmetic, random numbers, matrix operations'),
    w('Week 5', 'Text & OS Algorithms', 'Algorithms for text processors, language processors, operating systems, database management'),
    w('Week 6', 'NLP, Robotics & Divide-and-Conquer', 'Algorithms for natural language processing; robotics; theorem proving; divide and conquer'),
    w('Week 7', 'Dynamic Programming', 'Solution of recurrence equations; dynamic programming'),
  ],
  'CSC 407': [
    w('Week 1', 'Computing as a Profession', 'Computing as a profession; types of organizations affected by computers'),
    w('Week 2', 'Sociological Impact', 'Sociological impact of computers; individuals and computers'),
    w('Week 3', 'Computers Across Sectors', 'Computers as auditing tools; computers in banking, education, government, insurance, medical profession'),
    w('Week 4', 'Consultancy & Telecommunications', 'Consultancy services; telecommunications; computers and the law of information technology'),
    w('Week 5', 'Cyber Attacks & Terrorism', 'Computer attacks and cyber terrorism'),
    w('Week 6', 'Health & Environment', 'Contemporary health issues in the computing profession and environment: health hazards, ergonomics, protection and remedies'),
    w('Week 7', 'Term Paper & Guest Talks', 'Term paper on a chosen topic; expert-led sessions on the above topics'),
  ],
  'CSC 409': [
    w('Week 1', 'Foundations of HCI', 'Foundations of HCI: understanding and conceptualizing interaction; understanding users'),
    w('Week 2', 'Collaboration & Affective Design', 'Designing for collaboration and communication; affective aspects; interfaces and interactions'),
    w('Week 3', 'Data Gathering & Analysis', 'Data gathering, data analysis, interpretation, and presentation'),
    w('Week 4', 'Principles of GUI Design', 'Principles of GUI: process of interaction design; identifying needs and establishing requirements'),
    w('Week 5', 'Prototyping & Construction', 'Design, prototype, and construction; GUI toolkits'),
    w('Week 6', 'Human-Centred Evaluation', 'Human-centred software evaluation and development; software tools for modeling GUI'),
    w('Week 7', 'GUI Data Structures & Projects', 'Data structures for coding complex GUI systems; GUI design, evaluation, and programming projects'),
  ],
  'CSC 411': [
    w('Week 1', 'Operations Research Overview', 'Nature and scope of operations research'),
    w('Week 2', 'Linear Programming', 'Linear programming and graphical methods; sensitivity analysis; duality theory'),
    w('Week 3', 'Transportation & Network Analysis', 'Transportation and assignment problems; network analysis: CPM and PERT'),
    w('Week 4', 'Stochastic Processes & Inventory', 'Stochastic processes and Markov chains; inventory control theory and applications'),
    w('Week 5', 'Sequencing & Decision Theory', 'Sequencing and scheduling problems; decision theory; decision under uncertainty; decision-tree models'),
    w('Week 6', 'Investment & Resource Allocation', 'Investment appraisal; resource allocation; equipment replacement analysis'),
    w('Week 7', 'Reliability & Forecasting', 'Reliability of series/parallel systems; time series analysis and forecasting'),
    w('Week 8', 'Game Theory & Applications', 'Game theory and applications; dynamic programming problems; use of OR application packages; case studies and simulation'),
  ],
  'CSC 415': [
    w('Week 1', 'Wireless Protocols', 'Wireless communication protocols and mobile computing'),
    w('Week 2', 'Mobile Applications & Hardware', 'Mobile applications; mobile hardware systems and infrastructures'),
    w('Week 3', 'Mobile Software & Android', 'Mobile software systems; Android technology'),
    w('Week 4', 'Models of Mobile Computing', 'Models of mobile computing systems; cloud computing'),
    w('Week 5', 'Mobile Programming', 'Mobile computing programming systems'),
    w('Week 6', 'Design & Implementation', 'Design and implementation of mobile computing systems'),
  ],
  'IFT 405': [
    w('Week 1', 'Foundations of Research', 'Definition of research; scope and characteristics of research'),
    w('Week 2', 'Selecting a Research Topic', 'How to select research topics; planning for research'),
    w('Week 3', 'Data Collection Methods', 'Methods of data collection; instruments used in collecting information'),
    w('Week 4', 'Sampling & Research Design', 'Sampling procedures; research design and the nature of the research'),
    w('Week 5', 'Data Analysis & Hypothesis Testing', 'Methods of analyzing data and hypothesis testing; illustrative examples'),
    w('Week 6', 'Writing the Research Report', 'Guidelines for writing the research report; proposal and format for the completed project'),
    w('Week 7', 'Capstone Management', 'Integration of previously learned knowledge and skills in development, design, and presentation of a project'),
    w('Week 8', 'Project Planning & Scheduling', 'Project plan and justification; develop marketing strategy; design work; schedule and budget requirements'),
    w('Week 9', 'Status Reporting', 'Adjusting for unplanned occurrences; provision of status reports; chapters of the project report format'),
  ],
  'CSC 417': [
    w('Week 1', 'Digital System Design', 'Basic logic gates; digital system designs \u2014 combinational and sequential circuits'),
    w('Week 2', 'Registers & Firmware Concepts', 'Register, flip-flop, counters; microprogrammed architectures; principles of firmware engineering'),
    w('Week 3', 'Real-Time & Embedded Systems', 'Real-time and embedded system concepts; ROM programming; ROM size reduction techniques'),
    w('Week 4', 'Programmable Logic', 'Programmable logic arrays; field programmable gate arrays (FPGAs)'),
    w('Week 5', 'Microprocessor & Microcontroller Design', 'PROM/EPROM programmers; microprocessor-based design; microcontrollers'),
    w('Week 6', 'Hardware Description Languages', 'Wireless modem; hardware design using hardware description languages (HDLs)'),
    w('Week 7', 'Real-Time OS & Testing', 'Real-time operating systems; systems on a chip; system testing and fault detection'),
    w('Week 8', 'Embedded Networking & Projects', 'Embedded network devices; virtual machine approach to system design; introduction to real-time programming languages; case studies and design projects'),
  ],
  'CSC 419': [
    w('Week 1', 'Grammars & Recognizers', 'Grammars and languages; recognizers'),
    w('Week 2', 'Parsing Techniques', 'Top-down and bottom-up parsers'),
    w('Week 3', 'Runtime Storage Organization', 'Runtime storage organization; use of display in runtime storage organization'),
    w('Week 4', 'LR Grammars & Tables', 'LR grammars and analyzers; construction of LR tables'),
    w('Week 5', 'Symbol Tables & Storage Allocation', 'Organization of symbol table; storage allocation to run-time variables'),
    w('Week 6', 'Optimization & Code Generation', 'Optimization techniques; code generation'),
  ],
  'CSC 421': [
    w('Week 1', 'Database Development Review', 'Review of database development processes; enterprise modeling'),
    w('Week 2', 'Conceptual & Logical Design', 'Conceptual data modeling; logical database design'),
    w('Week 3', 'Physical Design & Implementation', 'Physical database design; database implementation and maintenance'),
    w('Week 4', 'Record Structure & File Organization', 'Record structure and file organization for relational, distributed, object-oriented, multimedia, deductive, temporal databases'),
    w('Week 5', 'UI & Report Design', 'Design of user interface, I/O, and report formats; standard query languages (SQL, QBE)'),
    w('Week 6', 'Transaction Processing', 'Design and implementation of algorithms for transaction files processing and reports generation'),
    w('Week 7', 'Automated Development & DBMS Study', 'Automated program and report generators; detailed study of a DBMS such as MS-Access, MySQL, Oracle, Sybase, DB2, IMS'),
    w('Week 8', 'Mini-Projects', 'Mini-projects on database system design and development'),
  ],
  'CSC 423': [
    w('Week 1', 'Concurrent Systems Concepts', 'Concurrent systems concepts; ACID properties of concurrent transactions'),
    w('Week 2', 'Process Structuring', 'Process structuring; multi-threaded processes; inter-process communications'),
    w('Week 3', 'Message Passing & Address Space', 'Process address space; asynchronous and synchronous message passing'),
    w('Week 4', 'Deadlock Handling', 'Deadlock and prevention algorithms; resource allocation graphs and matrices'),
    w('Week 5', 'Concurrency Control Strategies', 'Mutual exclusion; semaphores; conditional critical regions; monitors'),
    w('Week 6', 'Time-Stamp Ordering & Locking', 'Time-stamp ordering; two-phase locking; guided commands'),
    w('Week 7', 'Crash Recovery', 'Crashes and recovery strategies; concurrent programming languages: object models; shared monitors'),
    w('Week 8', 'Execution Scheduling', 'Concurrent execution conditions: task serialization; non-strict execution schedules; serialization graph'),
    w('Week 9', 'Language Features & OS Support', 'Features of concurrent programming languages (Concurrent Pascal, Concurrent-C, Modula, Turing Plus, Gypsy, PLITS); OS support for concurrent program development'),
  ],
  'CSC 413': [
    w('Week 1', 'Matrix Computations', 'Matrix types and computations; solution of linear and nonlinear systems of equations'),
    w('Week 2', 'Eigenvalue Problems', 'Eigenvalue/eigenvector problems; vector algebra'),
    w('Week 3', 'Numerical Interpolation', 'Numerical interpolations; function approximations; spline functions'),
    w('Week 4', 'Numerical ODEs & PDEs', 'Numerical solution of ordinary and partial differential equations; stability and convergence'),
    w('Week 5', 'Transforms & Error Analysis', 'Chebyshev functions; Fourier transforms, wavelet transforms; truncation error analysis'),
    w('Week 6', 'Matrix/Vector Computations', 'Multi-dimensional numerical interpolation; matrix/vector computations; eigenfunctions, singular value decomposition'),
    w('Week 7', 'Optimization & Mathematical Software', 'Numerical solution methods; numerical optimization; introduction to Mathematica, MathCAD, Maple'),
    w('Week 8', 'Applications & Projects', 'Projects on numerical computations with applications to image processing, data analysis, and scientific modeling'),
  ],
  'STA 451': [
    w('Week 1', 'Principles of Experimentation', 'Basic principles of experimentation; randomization, replication and blocking; local control'),
    w('Week 2', 'Basic Designs', 'Basic designs: completely randomized blocks, split plot; missing values'),
    w('Week 3', 'Relative Efficiency & Estimation', 'Relative efficiency; estimation and test of variance components'),
    w('Week 4', 'Multiple Comparisons', 'Multiple comparisons; departures from underlying assumptions'),
    w('Week 5', 'Applications', 'Applications to agriculture, biology, and industry'),
  ],

  // ==================== 500 LEVEL — HARMATTAN ====================

  'CSC 501': [
    w('Week 1', 'Development Process Models', 'Software development process models; requirements and specifications'),
    w('Week 2', 'Design Methodologies', 'Design methodologies: object-oriented, component-based, knowledge-based, agent-based, formal methods, prototyping'),
    w('Week 3', 'Data & Process Design', 'Data, process, and flow design methodologies; software metrics'),
    w('Week 4', 'Testing & Quality Assurance', 'Testing and quality assurance; software test automation'),
    w('Week 5', 'Maintenance & Standards', 'Software maintenance; software standards; IEEE and other standards'),
    w('Week 6', 'Project Management & CASE Tools', 'SE project management; CASE tools'),
    w('Week 7', 'Design Mini-Projects', 'Case studies and software design mini-projects for planning, control, communication, embedded systems, Internet, and agent-based applications'),
  ],
  'CSC 503': [
    w('Week 1', 'Organizational Structures', 'Organizational structures; leadership management functions: planning, decision, control, motivation'),
    w('Week 2', 'Information System Components', 'Structure and organization of information systems: hardware, software, staff structure'),
    w('Week 3', 'Enterprise Information Systems', 'Integrated enterprise information system design; management control'),
    w('Week 4', 'Decision Support & ERP', 'Enterprise decision support systems; ERP software such as SAP R/3'),
    w('Week 5', 'Processing Modes & Recovery', 'Information processing modes: batch, online, real-time; hardware/software failures and recovery strategies'),
    w('Week 6', 'Legal & IP Issues', 'Legal issues: copyright and intellectual property laws; OEM and vendors'),
    w('Week 7', 'Enterprise & Security Management', 'Managing computer installation; enterprise IT planning and implementing change; security issues'),
    w('Week 8', 'EDP Administration', 'Effective corporate placement of EDP personnel administration; technology of database management'),
    w('Week 9', 'Site Planning & Auditing', 'Site preparation; planning a new installation; evaluation of computer department; systems auditing; managerial stress'),
    w('Week 10', 'E-Commerce Case Studies', 'Case studies involving e-commerce systems development using electronic data interchange (EDI) software'),
  ],
  'CSC 505': [
    w('Week 1', 'AI Foundations & Agents', 'Background: AI and agents; AI definition and areas; agent definition, structure, and types'),
    w('Week 2', 'Search Strategies', 'Search: exhaustive search, heuristic search, local search (e.g. hill-climbing)'),
    w('Week 3', 'Constraint Satisfaction & Adversarial Search', 'Constraint satisfaction; adversarial search; search under uncertainty'),
    w('Week 4', 'Logical Reasoning', 'Logical reasoning: knowledge-based systems, reasoning, planning, fuzzy logic'),
    w('Week 5', 'Probabilistic Reasoning', 'Probabilistic reasoning: quantifying uncertainty, Bayesian networks, dynamic Bayesian networks'),
  ],
  'CSC 507': [
    w('Week 1', 'Information Theory', 'Introduction to information theory: sources, measures, entropy, coding techniques'),
    w('Week 2', 'Waveform & Transform Analysis', 'Introduction to waves analysis: Fourier series, Fourier transform, Z-transform'),
    w('Week 3', 'Data Conversion & Infrastructure', 'Analog/digital data conversion; data communication infrastructures'),
    w('Week 4', 'Communication Equipment', 'Data communication equipment: modems, hubs, bridges, and their characteristics'),
    w('Week 5', 'Transmission & Multiplexing', 'Synchronous and asynchronous transmission; multiplexing (FDM, TDM, PCM)'),
    w('Week 6', 'Error Detection & Networks', 'Error detection and correction; packet-switching data networks'),
    w('Week 7', 'Internet Protocols & Routing', 'Internet protocols; Internet protocol addressing; Internet virtual private networks; routing algorithms'),
    w('Week 8', 'ATM & Wireless LANs', 'Asynchronous transfer mode (ATM) network structure; wireless LANs; features of typical data communication software systems'),
  ],
  'CSC 509': [
    w('Week 1', 'Network System Models', 'Network system models; distributed computing'),
    w('Week 2', 'Mobile & Wireless Computing', 'Mobile and wireless computing; international standards for Internet-based systems'),
    w('Week 3', 'Network Database Design', 'Network database design and organization; client/server computing using the web'),
    w('Week 4', 'Network Security & Hosting', 'Network security measures; web programming; system hosting'),
    w('Week 5', 'Web Applications & Data Security', 'Database designs; media technologies; web security; building web applications'),
    w('Week 6', 'Design & Validation Tools', 'Tools for design, modelling, simulation, testing, and validation of Internet-based systems'),
  ],
  'CSC 511': [
    w('Week 1', 'Basic Definitions', 'Basic definitions: data, knowledge, intelligence, artificial intelligence'),
    w('Week 2', 'Knowledge Representation', 'Tree-structure representation of data/knowledge; intelligent search methods'),
    w('Week 3', 'Knowledge Engineering', 'Basic structure of knowledge-based systems technology; knowledge engineering: knowledge acquisition, representation schemes, inference mechanisms, explanation facilities'),
    w('Week 4', 'Subfields of AI', 'Introduction to subfields of AI: expert systems, fuzzy systems, genetic algorithms, genetic programming, machine learning'),
    w('Week 5', 'Reasoning & Game Playing', 'Symbolic logic and automated reasoning; game playing; robots and vision systems'),
    w('Week 6', 'AI Languages & Applications', 'AI programming languages and systems: Lisp, Prolog, Smalltalk, expert system shells; new trends; applications and case studies'),
  ],
  'CSC 513': [
    w('Week 1', 'Data Mining & Big Data Overview', 'Overview of data mining; data warehousing and OLAP; big data'),
    w('Week 2', 'Data Pre-processing', 'Data pre-processing; data cube computation and multi-dimensional data analysis'),
    w('Week 3', 'Mining Patterns & Associations', 'Mining frequent patterns, associations, and correlations'),
    w('Week 4', 'Data Classification Methods', 'Data classification methods (k-means, hierarchical method, density-based method)'),
    w('Week 5', 'Data Mining Algorithms', 'Data mining algorithms (data clustering, classification, prediction)'),
    w('Week 6', 'Databases for Data Mining', 'Databases for data mining; software benchmarking'),
    w('Week 7', 'Tools & Mini-Projects', 'Data mining software tools and applications (e.g. WEKA); data mining mini-projects for knowledge discovery'),
  ],
  'CSC 555': [
    w('Weeks 1-13', 'Final Year Project (Harmattan)', 'Each final-year student undertakes a computer science-related project, starting within the first four weeks of the Harmattan semester, working with an assigned supervisor'),
  ],
  'CSC 515': [
    w('Week 1', 'Microprocessor Specifications', 'Formal specifications of microprocessor functions, operations, and architecture'),
    w('Week 2', 'Comparing Microprocessors', 'Comparison of current microprocessors; multi-chip; I/O organization'),
    w('Week 3', 'Instruction Sets & Addressing', 'Assembler language; instruction sets; address modes'),
    w('Week 4', 'Bus Control & Interrupts', 'Bus control; stack operation; interrupt structures; program transfer'),
    w('Week 5', 'DMA & Microprocessor Types', 'DMA for microcomputers; types of microprocessors; uses of microprocessor, microcomputer networking'),
    w('Week 6', 'Interfacing & Real-Time Control', 'Microprocessor design for specific applications; interfacing microcomputer real-time control; laboratory exercises'),
  ],
  'CSC 517': [
    w('Week 1', 'Distributed System Models', 'Classification of distributed systems; distributed system models; communication protocols'),
    w('Week 2', 'Remote Access & Invocation', 'Remote access control; remote method invocation; stream-oriented communication'),
    w('Week 3', 'Synchronization & Global State', 'Synchronization; global state; election; distributed mutual exclusion'),
    w('Week 4', 'Database & Transaction Processing', 'Distributed database design; concurrency control; two- and three-phase commit protocol and query processing; distributed transactions'),
    w('Week 5', 'Naming & Replication', 'Domain naming schemes; naming and localization; replication; coherence; consistency models and protocols'),
    w('Week 6', 'Fault Tolerance & Security', 'Group communications; check points; fault tolerance; security access control; key management; data encryption'),
    w('Week 7', 'Distributed OS & File Systems', 'Distributed operating systems; distributed file system and services: NFS, Coda, etc.'),
    w('Week 8', 'Mobile & Network Computing', 'Mobile computing; distributed system and network programming'),
  ],
  'CSC 519': [
    w('Week 1', 'Web Server Administration', 'Web server administration; web development using content management systems'),
    w('Week 2', 'Computer Forensics & Auditing', 'Computer forensics; computer auditing'),
    w('Week 3', 'IT Project Development', 'Information technology project development and management'),
    w('Week 4', 'Enterprise Information Architecture', 'Architecture and organization of enterprise information systems; computer network administration'),
    w('Week 5', 'Multimedia & Teleconferencing', 'Multimedia systems; teleconferencing; smart IT devices/tools'),
    w('Week 6', 'Information Security & Recovery', 'Information security risks, analysis, and management; information disaster recovery'),
  ],
  'CSC 521': [
    w('Week 1', 'Classifying Programming Languages', 'Classification of high-level programming languages; language definition structure'),
    w('Week 2', 'Data Types & Structuring', 'Data types and structuring; review of basic data types including lists and trees'),
    w('Week 3', 'Control Structure & Runtime', 'Review of basic control structure and data flows; runtime considerations'),
    w('Week 4', 'Interpretation & Parsing', 'Interpretative languages; lexical analysis and parsing'),
    w('Week 5', 'Language Design Project', 'Language design project'),
  ],
  'STA 513': [
    w('Week 1', 'Ratio, Regression & Difference Estimation', 'Ratio, regression, and difference estimation procedures'),
    w('Week 2', 'Double & Interpenetrating Sampling', 'Double sampling; interpenetrating scheme'),
    w('Week 3', 'Multiphase & Multistage Sampling', 'Multiphase and multistage sampling'),
    w('Week 4', 'Cluster Sampling', 'Cluster sampling with unequal sizes; problem of optimal allocation with more than one item'),
    w('Week 5', 'Further Stratified Sampling', 'Further stratified sampling'),
  ],

  // ==================== 500 LEVEL — RAIN ====================

  'CSC 502': [
    w('Week 1', 'Formal Grammars & Languages', 'Review of formal grammar and languages; classification of grammars'),
    w('Week 2', 'Automata', 'Deterministic and non-deterministic automata; regular sets and regular expressions'),
    w('Week 3', 'Parsing & Sequential Machines', 'Closure properties; parsing; sequential machines and finite state transducers; state minimization'),
    w('Week 4', 'Pushdown Automata', 'Pushdown automata; pushdown transducer'),
    w('Week 5', 'Turing Machines', 'Turing machine as acceptor and transducer; universal Turing machine; Church thesis'),
    w('Week 6', 'Computability', 'Solvability and unsolvability; computable and non-computable functions; recursive functions; the halting problem'),
    w('Week 7', 'Abstract Models & Simulation', 'Relative power of formal models; abstract machine models design and software simulation exercises'),
  ],
  'CSC 504': [
    w('Week 1', 'Operating Modes & Display Control', 'Operating modes; the light pen; display control, converters, symbol generators, line generators'),
    w('Week 2', 'Display Hardware', 'Amplifiers; cathode ray tube; CRT recorders; direct-view storage tube; automatic mechanical plotting boards'),
    w('Week 3', 'Interactive Graphics & Transformations', 'Interactive graphics display software; three-dimensional rotation, translation, and perspective transformations'),
    w('Week 4', '3D Representation', 'Hidden-line removal; representation of three-dimensional objects, reticular surfaces, Coons patches, B-splines'),
    w('Week 5', 'Advanced Graphics & Color', 'State-of-the-art application in design, controls, and engineering analysis; computer graphics color management'),
    w('Week 6', 'Graphics Libraries', 'Computer graphics programming languages; use of advanced graphics libraries (OpenGL and/or DirectX)'),
    w('Week 7', 'Image Processing', 'Images from scanners and digital cameras; photo manipulation; optimizing images; image compression and decompression'),
    w('Week 8', 'Image Software & Databases', 'Software (e.g. Adobe Photoshop Elements) for image creation and image database management'),
  ],
  'CSC 506': [
    w('Week 1', 'Network Concepts', 'Network concepts: network structures, architectures, and protocols'),
    w('Week 2', 'Bandwidth & Channel Management', 'Storage, delay, multiplexing, bandwidth sharing and dynamic bandwidth management, QoS'),
    w('Week 3', 'Channel Access Control', 'Channel organization, framing, channel access control; PSPDN and integrated digital networks'),
    w('Week 4', 'OSI & TCP/IP', 'Open System Interconnection (OSI) and transmission control protocol/Internet protocol (TCP/IP)'),
    w('Week 5', 'Network Topologies & Access', 'Network topologies \u2014 LANs, WANs, terminal networks, broadcast and routed transmission; LAN contention and permission-based media access'),
    w('Week 6', 'MAC Protocols', 'Protocol, CSMA/CD, token ring, token bus, slatted ring, client/server models, RPC, FDDI'),
    w('Week 7', 'WAN Technologies', 'WAN circuit and packet switching, PSDN and ISDN, X.25; routing algorithms and protocol variations'),
    w('Week 8', 'Internetworking', 'Internetworking: resolution of protocol variations; repeaters, hubs, bridges, routers, gateways, protocol converters'),
    w('Week 9', 'Internet Technology & Projects', 'Introduction to Internet technology; Internet connectivity; services on the Internet; current trends and network performance evaluation; network modeling and simulation projects'),
  ],
  'CSC 508': [
    w('Week 1', 'Evaluation as Disciplined Enquiry', 'Evaluation as disciplined enquiry; an overview of models and conceptualization: a historical overview'),
    w('Week 2', 'Approaches to Evaluation', 'Planning alternative approaches to evaluation; assumptions underlying evaluation models and conceptualizations'),
    w('Week 3', 'Design Standards & Impact', 'Design standards; influence of models on information systems; impact of model building process'),
    w('Week 4', 'Discrepancy Model & Applications', 'Applications of the discrepancy model: CIPP, Stake Countenance, Scriven, Provus, Kammond, Alkin, Tyler, Stufflebeam'),
    w('Week 5', 'Performance Evaluation Techniques', 'Basic techniques of system performance evaluation: performance modeling, discrete events simulation'),
    w('Week 6', 'Simulation Validation & Queuing', 'Verification and validation of simulation models; analysis of simulation output; analysis of single-server queue and queuing networks'),
    w('Week 7', 'Case Studies', 'Modeling of computer systems and models; case studies of some real systems'),
  ],
  'CSC 510': [
    w('Week 1', 'Decision-Making Under Uncertainty', 'Review of probability and decision-making under uncertainty; maximum and minimum regret rules'),
    w('Week 2', 'Decision Trees & Forecasting', 'Decision trees; forecasting; regression analysis and time series analysis'),
    w('Week 3', 'Queuing & Inventory Models', 'Queuing models; inventory and scheduling systems'),
    w('Week 4', 'Hardware Modeling', 'Time flow mechanisms; mathematical models of computer I/O hardware devices using mass-spring-dashpot analogues'),
    w('Week 5', 'Simulation Program Design', 'Design of simulation program; analysis of results of simulation; validation of simulation models'),
    w('Week 6', 'Simulation Languages & Case Studies', 'Introduction to simulation language (e.g. SIMULA, QSB+); case studies of computer modeling, simulation, and forecasting in scientific, business, and industrial applications'),
  ],
  'CSC 514': [
    w('Week 1', 'Process Improvement', 'Topics from process improvement; software re-engineering'),
    w('Week 2', 'Configuration Management', 'Configuration management; formal specification'),
    w('Week 3', 'Cost Estimation & Architecture', 'Software cost estimation; software architecture'),
    w('Week 4', 'Patterns & Reuse', 'Software patterns; software reuse and open source development'),
  ],
  'CSC 512': [
    w('Week 1', 'IoT Overview & Cloud Architecture', 'General overview of Internet of Things (IoT); cloud technology: cloud computing and architecture'),
    w('Week 2', 'IoT Architecture & Protocols', 'Architecture of IoT; understanding IoT protocols'),
    w('Week 3', 'IoT in Business', 'IoT as applied in business; IoT business models and benefits; issues of IoT in business'),
    w('Week 4', 'Blockchain Technology', 'Blockchain technology: cryptocurrency technologies e.g. Bitcoin, Ethereum, litecoin, benefits and challenges'),
    w('Week 5', 'IoT Security', 'IoT device security mechanism; flexibility level of protection required for the IoT; challenges of securing IoT communication'),
    w('Week 6', 'Privacy & Education Applications', 'Privacy and user data; big data; education: e-learning tools (course management systems, game-based learning, online management systems, result processing)'),
    w('Week 7', 'Design & UX for IoT', 'Design/user experience: designing for predictive machine learning for the IoT; how to design successful IoT products; UX design for predictive mechanisms; other IoT applications; course minor project'),
  ],
  'CSC 556': [
    w('Weeks 1-13', 'Final Year Project (Rain)', 'Continuation of the final-year project; each student is assigned to a project supervisor; formal report submitted before second-semester examinations; project defended before the department and external examiner'),
  ],

};

const run = async () => {
  await connectDB();

  let updated = 0;
  let notFound = [];

  for (const [course_code, scheme_of_work] of Object.entries(SCHEME_OF_WORK)) {
    const course = await Course.findOneAndUpdate(
      { course_code },
      { $set: { scheme_of_work } },
      { new: true }
    );
    if (course) {
      updated += 1;
      console.log(`Updated: ${course_code} (${scheme_of_work.length} row${scheme_of_work.length === 1 ? '' : 's'})`);
    } else {
      notFound.push(course_code);
    }
  }

  console.log(`\nDone. ${updated} course(s) updated with a scheme of work.`);
  if (notFound.length) {
    console.log(`\n${notFound.length} course code(s) in this script don't match any course in the database:`);
    notFound.forEach((c) => console.log('  - ' + c));
  }

  await mongoose.connection.close();
  process.exit(0);
};

run().catch((error) => {
  console.error('Import failed:', error.message);
  process.exit(1);
});
